export const CART_ADD_CART_REQUEST = "CART_ADD_CART_REQUEST"
export const CART_GET_CART_REQUEST = "CART_GET_CART_REQUEST"
export const CART_UPDATE_CART_REQUEST = "CART_UPDATE_CART_REQUEST"
export const CART_REMOVE_CART_REQUEST= "CART_REMOVE_CART_REQUEST"



export const CART_ADD_CART_FAIL = "CART_ADD_CART_FAIL"
export const CART_GET_CART_FAIL = "CART_GET_CART_FAIL"
export const CART_UPDATE_CART_FAIL = "CART_UPDATE_CART_FAIL"
export const CART_REMOVE_CART_FAIL= "CART_REMOVE_CART_FAIL"



export const CART_ADD_CART_SUCCESS = "CART_ADD_CART_SUCCESS"
export const CART_GET_CART_SUCCESS = "CART_GET_CART_SUCCESS"
export const CART_UPDATE_CART_SUCCESS = "CART_UPDATE_CART_SUCCESS"
export const CART_REMOVE_CART_SUCCESS= "CART_REMOVE_CART_SUCCESS"


