export const ORDER_ADD_ORDER_REQUEST = "ORDER_ADD_ORDER_REQUEST"
export const ORDER_GET_ORDER_REQUEST = "ORDER_GET_ORDER_REQUEST"
export const ORDER_UPDATE_CART_REQUEST = "ORDER_UPDATE_ORDER_REQUEST"
export const ORDER_REMOVE_CART_REQUEST= "ORDER_REMOVE_ORDER_REQUEST"



export const ORDER_ADD_ORDER_FAIL = "ORDER_ADD_ORDER_FAIL"
export const ORDER_GET_ORDER_FAIL = "ORDER_GET_ORDER_FAIL"
export const ORDER_UPDATE_CART_FAIL = "ORDER_UPDATE_ORDER_FAIL"
export const ORDER_REMOVE_CART_FAIL= "ORDER_REMOVE_ORDER_FAIL"



export const ORDER_ADD_ORDER_SUCCESS = "ORDER_ADD_ORDER_SUCCESS"
export const ORDER_GET_ORDER_SUCCESS = "ORDER_GET_ORDER_SUCCESS"
export const ORDER_UPDATE_ORDER_SUCCESS = "ORDER_UPDATE_ORDER_SUCCESS"
export const ORDER_REMOVE_ORDER_SUCCESS= "ORDER_REMOVE_ORDER_SUCCESS"